# Generated by Django 5.0 on 2023-12-20 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="reg_mobile",
            new_name="reg_mob",
        ),
        migrations.RenameField(
            model_name="registration",
            old_name="reg_password",
            new_name="reg_pwd",
        ),
    ]
