# Generated by Django 5.0 on 2023-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0003_alter_registration_reg_mob_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=255)),
                ("contact_msg", models.CharField(max_length=255)),
            ],
        ),
    ]
