# Generated by Django 5.0 on 2024-01-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=255)),
                ("pro_price", models.FloatField()),
                ("pro_image", models.FileField(upload_to="")),
            ],
        ),
    ]
