# Generated by Django 5.0 on 2024-01-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0005_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pro_image",
            field=models.FileField(upload_to="products"),
        ),
    ]
