# Generated by Django 5.0 on 2024-01-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0008_product_pro_catid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_user", models.CharField(max_length=255)),
                ("cart_pid", models.IntegerField(null=True)),
                ("cart_name", models.CharField(max_length=255)),
                ("cart_price", models.FloatField(null=True)),
                ("cart_image", models.FileField(upload_to="")),
                ("cart_qty", models.IntegerField()),
                ("cart_amount", models.FloatField()),
            ],
        ),
    ]
