# Generated by Django 5.0.3 on 2024-03-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0010_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_image",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="order",
            name="order_pid",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_proname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_qty",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_user",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
