# Generated by Django 5.0.3 on 2024-03-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0011_order_order_amount_order_order_image_order_order_pid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_payment",
            field=models.FloatField(null=True),
        ),
    ]
