# Generated by Django 5.0.3 on 2024-03-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page5", "0012_order_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_payment",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
